### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by hparkersd**
Added two new page links per Alan's suggestions.

### CODE REVIEW

**Comment by n2ygk** [comment]
These edits should be part of PR #39, not a new PR.

**Comment by hparkersd** [comment]
I think that is why you are meeting with me. :)
Heather

Heather J. Parker ***@***.***KM6ZQB Amateur ExtraGLAARG VE#2092My Upcoming Exams
 

    On Thursday, April 29, 2021, 5:18:55 PM PDT, Alan Crosswell ***@***.***> wrote:  
 
 


These edits should be part of PR #39, not a new PR.

**Comment by n2ygk** [comment]
Uh huh:-)

**Comment by hparkersd** [comment]
Duplicate as changes have been moved to previous request.

**Comment by hparkersd** [comment]
Hi Alan,

Thanks for the help.  I had trouble with the links so I changed them back to the full link.  

Have a good trip and what do you plan to do out in LA?

Heather

**Pull request closed without merging**
