### PR TITLE
Linking to new page SandboxDummies  

### PR DESCRIPTION
**Pull request by hparkersd**
Updated pages to include links to new page.

### CODE REVIEW

**Comment by hparkersd** [comment]
Maybe hold off on merging this.  Not sure how to make changes now.   I need to fix the linking I think.

**Comment by n2ygk** [comment]
You can mark as draft or add WIP: to the title to defer reviews. You can
also explicitly request a review by assigning Nick:-)

**Comment by hparkersd** [comment]
Thanks!  I will have to figure out how to do that, but for now it is ready to go.  I updated the file name and it should match now.

Heather

**Comment by hparkersd** [comment]
What is the deal with the failing?  How do I fix that?

**Comment by hparkersd** [comment]
Quick review this before I mess it up.

**Review by nkbooth — APPROVED** [review]

**Pull request merged**
