### PR TITLE
Feature/callsign verify faq

### PR DESCRIPTION
**Pull request by taxilian**
This seems to be needed

### CODE REVIEW

**Comment by n2ygk** [comment]
Needs to be linked to docs/ve/ I think

**Comment by taxilian** [comment]
I think I'd like to keep this in a more central location -- for one thing I'm going to be linking to it externally and I need it to not move. How strongly do you feel about that location suggestion?

**Comment by taxilian** [comment]
I think I'm going to go ahead and make an executive decision on this one =] I need it in there and I need it to not move. the link will only go to beta/alpha today, so we can do more tweaking later, but I need to not be blocked on this.

**Comment by n2ygk** [comment]
By not linking it from a ToC it's not findable.

**Pull request merged**
